### ISSUE TITLE
小米14体验增强版Beta系统下，模块功能失效

### ISSUE THREAD

**Issue by Puppet357** [YifePlayte/Mi-Use-AOSP-Share-Sheet#3]
系统版本：OS1.1.3.0.VNCCNXM.BETA
ROOT方案：KernelSU 11928
Zygisk实现：ZygiskNext 1.2.0-Preview2 ( 391-adec5b7-release )
问题表现：模块无效果，仍然保持系统原有分享菜单界面，暂未发现其他Bug
原因分析：猜测是系统底层升级Android15导致模块失效

补充：不排除后续系统底层或基线有其他改变，为避免重复工作，可以考虑延迟更新，本条仅反馈问题

**Comment by YifePlayte** [comment]
Android 15 HyperOS 2 将分享/打开方式解耦为 IntentResolver 组件，不再需要zygisk模块，可使用lsposed模块实现此功能。此模块将停止开发。
